# 1. Database Connection (Transaction Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.atlxlghgfzscgyrlbzhd
spring.datasource.password=123Qqwewsaw3
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Important: Hikari connection settings for Pooler
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.keepaliveTime=30000